### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GiulianoBeltrami** [GiulianoBeltrami/CryptoAPP#1]
**Componente exchange**
_Layout_
- [x] Criação da table
- [ ] Formatação da table
- [ ] Cores da table
- [ ] Table que abre e fechar
- [ ] Table responsiva
- [ ] Formatação do texto interno da table

_Funcionalidades_
- [ ] Serviço redux
- [ ] Consumo da API
